### ISSUE TITLE
Not able to run application on Android 12+ or API level 33+

### ISSUE THREAD

**Issue by h1-squirtle** [payatu/BugBazaar#56]
BugBazaar Android application is not opening on Android 12+ and API level 33+. When I installed and clicked on application icon, it gets opened and closed quickly. App might be crashing.

I have checked on lower API levels, its working fine there.

**Comment by banditAmit** [comment]
@h1-squirtle  Thank you for bringing the issue to our attention! we are  investigating  &  working on a fix to enhance your experience.

**Comment by banditAmit** [comment]
Thanks for reporting, I see Android now has a [2.0.0-rc01] version now. We will look into upgrading to this soon.

In the meantime you can use this version in your app by simply adding it to your app/build.gradle.

`    implementation "androidx.work:work-runtime:2.0.0-rc01" `

**Comment by banditVedant** [comment]
@h1-squirtle  Thank you for reporting this issue. The issue has been fixed and latest apk with fix can be found in release section.
