### ISSUE TITLE
Build error : 'Q' is not a valid file-based ressource (QRCode.png)

### ISSUE THREAD

**Issue by sehno** [payatu/BugBazaar#62]
Hello,

I have a build error when i try to run the application : 

```
'Q' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
```

It's seems that it come from the QRCode.png.

Thank you.

**Comment by banditVedant** [comment]
This issue has been resolved now. The drawable directory had 2 files named QR.png and QRCode.png. As per android's documentation, filenames in drawable directory should be lower case always. These filenames with uppercase letters was causing issue during application build and compilation.

The master branch is updated with this fix now.

**Comment by banditVedant** [comment]
This issue is closed.
